name: taxi_app
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.1.7
  http: ^0.13.4
  firebase_core: ^2.23.0
  firebase_auth: ^4.14.1
  cloud_firestore: ^4.13.2
  avatar_glow: ^2.0.2
  animated_text_kit: ^4.2.1
  flutter_onboard: ^2.0.0
  flutter_polyline_points: ^1.0.0
  fluttertoast: ^8.0.9
  geolocator: ^10.1.0
  shared_preferences: ^2.0.15
  flutter_google_places: ^0.3.0
  google_api_headers: ^1.3.0
  map_picker: ^0.0.3
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
 
  uses-material-design: true

  assets:
    - assets/
  

